version: '3.8'

services:

  backend:
    image: mleonel51/mern-backend:latest #use the backend image created and uploaded to DockerHub by github workflow instead of build:  
    container_name: mern-backend-container
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env #considering i manually ssh into ec2 and insert .env file inside ~/mern-deploy folder

  frontend:
    image: mleonel51/mern-frontend:latest #use the frontend image created and uploaded to DockerHubby github workflow instead of build: 
    container_name: mern-frontend-container
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
